
name: provision-nonprod

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy the environment'
        required: false
        default: 'false'

jobs:
  provision-nonprod-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install Terraform
      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip
          unzip terraform_1.7.4_linux_amd64.zip
          chmod +x terraform
          sudo mv terraform /usr/local/bin/terraform

      # Install terragrunt
      - name: Install Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.55.11/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      # Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Run terragrunt provision
      - name: Terragrunt Provision
        run: |
          if [[ "${{ github.event.inputs.destroy }}" == "true" ]]; then
            cd environments
            terragrunt run-all destroy -auto-approve -terragrunt-non-interactive
          fi
          if [[ "${{ github.event.inputs.destroy }}" == "false" ]]; then
            cd environments
            terragrunt run-all apply -auto-approve -terragrunt-non-interactive
          fi
          if [[ "${{ github.event.inputs.destroy }}" != "true" && "${{ github.event.inputs.destroy }}" != "false" ]]; then
            echo "Error: destroy must be 'true' or 'false'"
            exit 1
          fi
