# This is a basic workflow to help you get started with Actions

name: provision-nonprod

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Get inputs
input:
  environment:
    description: 'Environment to provision (all, dev, test, uat)'
    required: true
    default: 'all'
  destroy:
    description: 'Destroy the environment'
    required: false
    default: 'false'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  provision-nonprod-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # # Install Terraform
      # - name: Install Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     terraform_version: 1.7.4

      # Install Terraform
      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip
          unzip terraform_1.7.4_linux_amd64.zip
          chmod +x terraform
          sudo mv terraform /usr/local/bin/terraform

      # Install terragrunt
      - name: Install Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.55.11/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      # Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Run terragrunt provision
      - name: Terragrunt Provision
      if: ${{ github.event.inputs.destroy == 'false' }}
        run: |
          cd environments
          terragrunt run-all apply -auto-approve -terragrunt-non-interactive
      else:
        run: |
          cd environments
          terragrunt run-all destroy -auto-approve -terragrunt-non-interactive